### ISSUE TITLE
unrendered css appears in tooltips

### ISSUE THREAD

**Issue by selfagency** [deepscan/atom-deepscan#2]
as shown in the screenshot below, when you hover over an error or warning and the tooltip appears, you see not just the deep scan warning but the unrendered stylesheet.

![screenshot 2018-09-28 00 32 14](https://user-images.githubusercontent.com/2541728/46188271-1c557880-c2b6-11e8-85c9-6c66ed9f55f8.png)

my suspicion is this is a consequence of the fact that i use the atom-ide package which replaces the standard linter with an enhanced diagnostics panel. you may want to add support for it, if that is the case, as atom-ide has nearly 800,000 downloads.

**Comment by cimfalab** [comment]
Oops,
I had the same problem after installing atom-ide-ui 0.13.0.
Thanks a heap for your issue and thoughtful suspicion.

I will try to find a solution.

**Comment by cimfalab** [comment]
Hello, I just published a 1.4.7 package.

Unfortunately, I couldn't find a decent solution.
atom-ide-ui package seems to have limitations:
 - [Full description is shown by default instead of collapsed way](https://github.com/facebook-atom/atom-ide-ui/issues/40)
 - [Raw HTML is not rendered](https://github.com/facebook-atom/atom-ide-ui/issues/99)

So as a workaround, I added an option to show/hide a full description.
![image](https://user-images.githubusercontent.com/762690/46200876-bf0d0600-c34d-11e8-9c63-110b44eb7425.png)

You can toggle off to hide a full description about detailed rule information.
After reopening the file (if the file was open), you can see only an issue message.

I think more specific and elegant solution is to consume the datatip service of 'atom-ide-ui' package but did not want to have a dependency now. :thinking:

I hope that you've found this update helpful.
If you have any questions, leave a comment.

**Comment by selfagency** [comment]
thanks so much!
